### ISSUE TITLE
block: phone/integrations/features search filter

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#14]
![image](https://user-images.githubusercontent.com/171559/236474633-77f2a68e-a3f0-4447-9cac-3d1344fc061c.png)

https://www.vonage.com/unified-communications/integrations/
![image](https://user-images.githubusercontent.com/171559/236475659-c2631889-7ade-4b7d-9273-4eb9fcc1e44b.png)

https://www.vonage.com/unified-communications/features/
![image](https://user-images.githubusercontent.com/171559/236476014-36c98d51-5a5b-4d2d-91ca-3c4dc4f426d1.png)

looks like it has an API call to fetch json.

**Comment by synox** [comment]
Depends on https://github.com/hlxsites/Vonage/issues/92
