### ISSUE TITLE
Need to fix slim promo on small-business page

### ISSUE THREAD

**Issue by david-granberg** [hlxsites/Vonage#140]
Compare: https://www.vonage.com/unified-communications/small-business/
![image](https://github.com/hlxsites/Vonage/assets/126118840/fc186473-1629-41ba-bd45-2c525ebe3154)

to: https://main--vonage--hlxsites.hlx.page/unified-communications/small-business
![image](https://github.com/hlxsites/Vonage/assets/126118840/2dac422c-6585-48d6-bffe-2631418a0dc7)

**Comment by rrusher** [comment]
https://small-biz--vonage--hlxsites.hlx.page/unified-communications/small-business

Addressed in #160
