### ISSUE TITLE
block: trustpilot small

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#25]
tweak the trustpilot block to accomodate this:
![image](https://github.com/hlxsites/Vonage/assets/171559/671ba4cc-f66c-48ea-96fa-34d254650184)

**Comment by dkuntze** [comment]
FYI there already is a block "trustpilot" that can be augmented here.

**Comment by rrusher** [comment]
The goal is to update the content in the widget to remove all but the stars and a link to TrustPilot?
Current widget:
<img width="723" alt="Screenshot 2023-06-05 at 11 53 02 AM" src="https://github.com/hlxsites/Vonage/assets/6796243/6b0f84b9-a9e1-4a6b-ac12-ed411031af85">

Are we to do the same for the Mobile view?
<img width="385" alt="Screenshot 2023-06-05 at 11 53 53 AM" src="https://github.com/hlxsites/Vonage/assets/6796243/0b7f1334-e4a1-40be-b702-cb9517c2aaac">

**Comment by rrusher** [comment]
The TrustPilot widget is designed to be customized through the [site](https://support.trustpilot.com/hc/en-us/articles/203840826-Add-a-TrustBox-to-a-webpage) or their [API](https://support.trustpilot.com/hc/en-us/articles/4404467354898-Create-a-custom-TrustBox-widget-using-Trustpilot-APIs).

TrustPilot customizations have [guidelines](https://support.trustpilot.com/hc/en-us/articles/202319278-Trustpilot-APIs-Service-Review-Integration-Guidelines) that are not consistent with this Issue's design requested in the first comment.

The recommended path is to customize the widget via TrustPilot.
