### ISSUE TITLE
Style: Columns variations

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#31]
![image](https://github.com/hlxsites/Vonage/assets/171559/a4320f86-85e0-4712-b0fd-16be100358fe)
![image](https://github.com/hlxsites/Vonage/assets/171559/c031ac66-9938-4ab3-a3c8-022417684e2a)
https://www.vonage.com/unified-communications/integrations/
![image](https://github.com/hlxsites/Vonage/assets/171559/8e0a1737-9afb-4275-9dad-d96e7bf04ca2)

**Comment by dkuntze** [comment]
the middle one looks like it might be custom block.

**Comment by rrusher** [comment]
@dkuntze The first image is called a "case study" and is located halfway down on: https://www.vonage.com/unified-communications/. I can see it as a variation of the `columns` block.

The second and third are both variations of the `landing-page-hero` block.

**Comment by david-granberg** [comment]
Don't think that this issue is needed any longer as the landing-page-hero block has been implemented as well as the case-study one.
