### ISSUE TITLE
Blocks: landing page hero

### ISSUE THREAD

**Issue by david-granberg** [hlxsites/Vonage#47]
![image](https://github.com/hlxsites/Vonage/assets/126118840/d5b2ac1e-f790-4f38-94cd-72e1e8b0ba43)

Noting that the right column has a video that launches in a popout div and that the main image is a composite of two images where the text bubble is overlaid onto the background image, but that image is a separate overlay div element positioned absolutely over the landing page hero, so likely shouldn't be included in the section structure and should instead be a separate block

**Comment by dkuntze** [comment]
@david-granberg :
![image](https://github.com/hlxsites/Vonage/assets/171559/228eb584-7da7-4b1a-bc9a-ca1236da5451)
