### ISSUE TITLE
cards: (card-link)

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#54]
<img width="1442" alt="image" src="https://github.com/hlxsites/Vonage/assets/171559/2a61640e-fac9-4555-a9db-e5434e682273">
https://www.vonage.com/unified-communications/

<img width="559" alt="image" src="https://github.com/hlxsites/Vonage/assets/171559/150ba7b4-46eb-4790-bf1b-0dd5d82f0fec">
<img width="673" alt="image" src="https://github.com/hlxsites/Vonage/assets/171559/c91c05e9-51da-4678-a684-79fc3624364b">

**Comment by jimaldous** [comment]
Renamed from cards: (card-image-3-up) to match the class that I added, card-link. This better describes what we have in this case, the whole card acting as the anchor for the associated link (pulled from the card body).
