### ISSUE TITLE
hero form

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#57]
![image](https://github.com/hlxsites/Vonage/assets/171559/3329490e-137e-47b2-a8a8-a013c39c5ed4)

on most pages.

use the reusable form fragments that can/are stored in the repo (or create them).

Pages: 
- https://www.vonage.com/unified-communications/ ("Chat with Sales", more fields)
- https://www.vonage.com/unified-communications/features/
- https://www.vonage.com/unified-communications/features/desktop/
- https://www.vonage.com/unified-communications/features/vonage-meetings/
- https://www.vonage.com/unified-communications/features/business-sms/
- https://www.vonage.com/unified-communications/features/mobile-app/
- https://www.vonage.com/unified-communications/features/call-blocking/
- https://www.vonage.com/unified-communications/features/call-forward/
- https://www.vonage.com/unified-communications/features/voicemail-to-email/
- https://www.vonage.com/unified-communications/features/sd-wan
- https://www.vonage.com/unified-communications/business-phones/

Submissions: 
- Sends POST to https://ww3.business.vonage.com/l/7772/2020-01-14/9tkvjb?success_location=https%3A%2F%2Fwww.vonage.com%2Fbin%2Fvonage%2Fapi%2Fform-handler.success&error_location=https%3A%2F%2Fwww.vonage.com%2Fbin%2Fvonage%2Fapi%2Fform-handler.error
- Above -> Redirects to GET to https://www.vonage.com/bin/vonage/api/form-handler.success
- Sends POST to https://www.vonage.com/bin/vonage/api/webinar-registration

**Comment by fperez-leappoint** [comment]
checking this one out

**Comment by dkuntze** [comment]
@fperez-leappoint how is it progressing?
