### ISSUE TITLE
css: cards

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/Vonage#6]
Cards (gradient-shadow)
![image](https://user-images.githubusercontent.com/171559/235963479-ab3fc631-2c92-4d14-a648-185d8b9c351a.png)
cards: (card-image-3-up) #54 
![image](https://user-images.githubusercontent.com/171559/235963552-bc161781-565b-4359-91f7-c8fd79856b01.png)
![image](https://user-images.githubusercontent.com/171559/235963631-b7b56c91-c9d1-45f0-80b8-819b143ef6c8.png)

**Comment by dkuntze** [comment]
Note: some of these are just tweaks to existing classes.
cards: (card-image-3-up) is issue #54

**Comment by rrusher** [comment]
cards (gradient-shadow) from the `Unified Communications` page looks like this:
<img width="319" alt="Screenshot 2023-06-12 at 3 56 52 PM" src="https://github.com/hlxsites/Vonage/assets/6796243/698a384f-bfd2-43ac-9d74-79dfd13e695f">
