### ISSUE TITLE
Address padding between sections

### ISSUE THREAD

**Issue by jimaldous** [hlxsites/Vonage#65]
The current default top and bottom padding for `section` elements, as set in "styles.css" is 9.6rem (96px). On at least the main `unified-communications` page this is causing 192px of vertical padding between sections, some of which don't have much content. This makes for a page that is more vertically spread out than the vonage.com source.

Proposal: Reduce the default top and bottom padding and/or consider combining some content of adjacent sections into single sections.

**Comment by david-granberg** [comment]
Yup I was just noting this after I addressed some spacing issues within the header and had planned to put an issue in to address this myself.  So seeing this I'll go ahead and take this one instead :D  Thanks!
